# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZIiWHu_DjDoak8vUd0CEoTiBnaT2cGUF
"""

from hashlib import sha256
MAX_NONCE = 100000000000000

def SHA256(text):
  return sha256(text.encode("ascii")).hexdigest()

def mine(block_number, transactions,previous_hash,prefix_zeroes):
  prefix_str = '0'*prefix_zeroes
  for nonce in range(MAX_NONCE):
     text = str(block_number) + transactions + previous_hash + str(nonce)
     new_hash = SHA256(text)
     if new_hash.startswith(prefix_str):
        print(f'Yay! Successfully mined bitcoined with nonce value:{nonce}')
        return new_hash
  raise BaseException(f"couldn't find correct has after trying {MAX_NONCE} times")
  

if __name__ == '__main__':
  transactions = '''
  Dhaval->Bhavin->20
  Mando->Cara->45
  '''
  difficulty = 7
  import time
  start = time.time()
  new_hash = mine(5,transactions,'759831720aa978c890b11f62ae49d2417f600f26aaa51b3291a8d21a4216582a',difficulty)
  total_time = str((time.time() - start))
  print(f"end mining. Mining took : {total_time} seconds")
  print(new_hash)